<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="mothership" failures="4" tests="10" name="ToDo List App Tests" time="100.601" errors="0" timestamp="2025-06-01T03:51:56 WIB">
  <testcase classname="com.example.tests.ToDoListTest" name="testAppLaunch" time="0.398"/>
  <testcase classname="com.example.tests.ToDoListTest" name="testAddNewTask" time="4.069"/>
  <testcase classname="com.example.tests.ToDoListTest" name="testAddMultipleTasks" time="15.149">
    <failure type="java.lang.AssertionError" message="Task should be present: Task 3 - Create Presentation expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Task should be present: Task 3 - Create Presentation expected [true] but found [false]
at com.example.tests.ToDoListTest.testAddMultipleTasks(ToDoListTest.java:80)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testAddMultipleTasks -->
  <testcase classname="com.example.tests.ToDoListTest" name="testMarkTaskCompleted" time="5.885">
    <failure type="java.lang.AssertionError" message="Completed task count should increase by 1 expected [1] but found [0]">
      <![CDATA[java.lang.AssertionError: Completed task count should increase by 1 expected [1] but found [0]
at com.example.tests.ToDoListTest.testMarkTaskCompleted(ToDoListTest.java:107)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- testMarkTaskCompleted -->
  <testcase classname="com.example.tests.ToDoListTest" name="testDeleteSpecificTask" time="3.857">
    <failure type="java.lang.AssertionError" message="Task should exist before deletion expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Task should exist before deletion expected [true] but found [false]
at com.example.tests.ToDoListTest.testDeleteSpecificTask(ToDoListTest.java:121)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteSpecificTask -->
  <testcase classname="com.example.tests.ToDoListTest" name="testDeleteTaskCancel" time="14.977">
    <failure type="java.lang.AssertionError" message="Task should still exist after canceling delete expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Task should still exist after canceling delete expected [true] but found [false]
at com.example.tests.ToDoListTest.testDeleteTaskCancel(ToDoListTest.java:168)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteTaskCancel -->
  <testcase classname="com.example.tests.ToDoListTest" name="testClearAllTasks" time="15.885"/>
  <testcase classname="com.example.tests.ToDoListTest" name="testEmptyTaskValidation" time="3.325"/>
  <testcase classname="com.example.tests.ToDoListTest" name="testDuplicateTaskValidation" time="8.029"/>
  <testcase classname="com.example.tests.ToDoListTest" name="testTaskCounterAccuracy" time="19.55"/>
</testsuite> <!-- ToDo List App Tests -->
